# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _hash
else:
    import _hash

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class buffer(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, nelements):
        _hash.buffer_swiginit(self, _hash.new_buffer(nelements))
    __swig_destroy__ = _hash.delete_buffer

    def __getitem__(self, index):
        return _hash.buffer___getitem__(self, index)

    def __setitem__(self, index, value):
        return _hash.buffer___setitem__(self, index, value)

    def cast(self):
        return _hash.buffer_cast(self)

    @staticmethod
    def frompointer(t):
        return _hash.buffer_frompointer(t)

# Register buffer in _hash:
_hash.buffer_swigregister(buffer)

def buffer_frompointer(t):
    return _hash.buffer_frompointer(t)

class Hash(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def __call__(self, *args):
        return _hash.Hash___call__(self, *args)

    def add(self, *args):
        return _hash.Hash_add(self, *args)

    def get_hash(self):
        return _hash.Hash_get_hash(self)

    def reset(self):
        return _hash.Hash_reset(self)
    __swig_destroy__ = _hash.delete_Hash

# Register Hash in _hash:
_hash.Hash_swigregister(Hash)

class SHA256(Hash):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    BlockSize = _hash.SHA256_BlockSize
    HashBytes = _hash.SHA256_HashBytes

    def __init__(self):
        _hash.SHA256_swiginit(self, _hash.new_SHA256())

    def __call__(self, *args):
        return _hash.SHA256___call__(self, *args)

    def add(self, *args):
        return _hash.SHA256_add(self, *args)

    def get_hash(self):
        return _hash.SHA256_get_hash(self)

    def get_raw_hash(self):
        return _hash.SHA256_get_raw_hash(self)

    def reset(self):
        return _hash.SHA256_reset(self)
    __swig_destroy__ = _hash.delete_SHA256

# Register SHA256 in _hash:
_hash.SHA256_swigregister(SHA256)



