# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_py_lib')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_py_lib')
    _py_lib = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_py_lib', [dirname(__file__)])
        except ImportError:
            import _py_lib
            return _py_lib
        try:
            _mod = imp.load_module('_py_lib', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _py_lib = swig_import_helper()
    del swig_import_helper
else:
    import _py_lib
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

AESKeyLength_AES_128 = _py_lib.AESKeyLength_AES_128
AESKeyLength_AES_192 = _py_lib.AESKeyLength_AES_192
AESKeyLength_AES_256 = _py_lib.AESKeyLength_AES_256
class AES(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, AES, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, AES, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _py_lib.new_AES(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def EncryptECB(self, *args):
        return _py_lib.AES_EncryptECB(self, *args)

    def DecryptECB(self, *args):
        return _py_lib.AES_DecryptECB(self, *args)

    def EncryptCBC(self, *args):
        return _py_lib.AES_EncryptCBC(self, *args)

    def DecryptCBC(self, *args):
        return _py_lib.AES_DecryptCBC(self, *args)

    def EncryptCFB(self, *args):
        return _py_lib.AES_EncryptCFB(self, *args)

    def DecryptCFB(self, *args):
        return _py_lib.AES_DecryptCFB(self, *args)

    def printHexArray(self, a, n):
        return _py_lib.AES_printHexArray(self, a, n)

    def printHexVector(self, a):
        return _py_lib.AES_printHexVector(self, a)
    __swig_destroy__ = _py_lib.delete_AES
    __del__ = lambda self: None
AES_swigregister = _py_lib.AES_swigregister
AES_swigregister(AES)

class Hash(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Hash, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Hash, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def __call__(self, *args):
        return _py_lib.Hash___call__(self, *args)

    def add(self, *args):
        return _py_lib.Hash_add(self, *args)

    def get_hash(self):
        return _py_lib.Hash_get_hash(self)

    def reset(self):
        return _py_lib.Hash_reset(self)
    __swig_destroy__ = _py_lib.delete_Hash
    __del__ = lambda self: None
Hash_swigregister = _py_lib.Hash_swigregister
Hash_swigregister(Hash)
cvar = _py_lib.cvar
sbox = cvar.sbox
inv_sbox = cvar.inv_sbox
GF_MUL_TABLE = cvar.GF_MUL_TABLE
CMDS = cvar.CMDS
INV_CMDS = cvar.INV_CMDS

class SHA256(Hash):
    __swig_setmethods__ = {}
    for _s in [Hash]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, SHA256, name, value)
    __swig_getmethods__ = {}
    for _s in [Hash]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, SHA256, name)
    __repr__ = _swig_repr
    BlockSize = _py_lib.SHA256_BlockSize
    HashBytes = _py_lib.SHA256_HashBytes

    def __init__(self):
        this = _py_lib.new_SHA256()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def __call__(self, *args):
        return _py_lib.SHA256___call__(self, *args)

    def add(self, *args):
        return _py_lib.SHA256_add(self, *args)

    def get_hash(self, *args):
        return _py_lib.SHA256_get_hash(self, *args)

    def reset(self):
        return _py_lib.SHA256_reset(self)
    __swig_destroy__ = _py_lib.delete_SHA256
    __del__ = lambda self: None
SHA256_swigregister = _py_lib.SHA256_swigregister
SHA256_swigregister(SHA256)

CON_BACKSPACE = _py_lib.CON_BACKSPACE
CON_RETURN = _py_lib.CON_RETURN

def getpass(*args):
    return _py_lib.getpass(*args)
getpass = _py_lib.getpass
# This file is compatible with both classic and new-style classes.


